language: ruby
cache: bundler
services:
  - docker
before_install:
  - gem update --system
  - gem install bundler
  - docker-compose build
script:
  - bundle exec rake
  - docker-compose run inferno bundle exec rake
  - bundle exec rubocop
notifications:
  email:
    recipients:
      - inferno@groups.mitre.org
    on_failure: change
